use clap::{Args, Subcommand, ValueEnum};

#[derive(Args)]
pub struct TlsArgs {
    #[command(subcommand)]
    pub command: TlsCommand,
}

#[derive(Subcommand)]
pub enum TlsCommand {
    /// Print a Caddyfile that terminates TLS for HOST and proxies to the local Hiveloom upstream.
    ///
    /// Hiveloom does not install Caddy or apply the configuration — you pipe the output
    /// where you want it. See https://docs.hiveloom.cloud/deploy/vps for the full recipe.
    Render(RenderArgs),
}

#[derive(Args)]
pub struct RenderArgs {
    /// Public hostname that will terminate TLS (e.g. hiveloom.example.com).
    /// DNS for this hostname must already point at the VPS; Hiveloom does not verify it.
    #[arg(long)]
    pub host: String,

    /// Contact email used by Let's Encrypt for renewal notices.
    #[arg(long)]
    pub email: String,

    /// ACME environment. Use `staging` during testing to avoid Let's Encrypt rate limits.
    #[arg(long, value_enum, default_value_t = AcmeEnv::Production)]
    pub acme_env: AcmeEnv,

    /// Hiveloom upstream port Caddy should proxy to.
    #[arg(long, default_value_t = 3000)]
    pub upstream_port: u16,
}

#[derive(Copy, Clone, ValueEnum)]
pub enum AcmeEnv {
    Production,
    Staging,
}

impl AcmeEnv {
    fn acme_ca(self) -> &'static str {
        match self {
            AcmeEnv::Production => "https://acme-v02.api.letsencrypt.org/directory",
            AcmeEnv::Staging => "https://acme-staging-v02.api.letsencrypt.org/directory",
        }
    }
}

pub async fn run(args: TlsArgs) -> anyhow::Result<()> {
    match args.command {
        TlsCommand::Render(r) => {
            print!("{}", render_caddyfile(&r.host, &r.email, r.acme_env, r.upstream_port));
            Ok(())
        }
    }
}

fn render_caddyfile(host: &str, email: &str, acme_env: AcmeEnv, upstream_port: u16) -> String {
    format!(
        "# Caddyfile for Hiveloom — generated by `hiveloom tls render`
# Put this at /etc/caddy/Caddyfile.d/hiveloom.caddy (or append to your Caddyfile) and run:
#   sudo systemctl reload caddy
# Caddy handles Let's Encrypt issuance and renewal automatically.

{{
    email {email}
    acme_ca {acme_ca}
}}

{host} {{
    encode zstd gzip

    reverse_proxy 127.0.0.1:{upstream_port} {{
        header_up Host {{host}}
        header_up X-Forwarded-Host {{host}}
        header_up X-Forwarded-Proto https
        header_up X-Forwarded-For {{remote_host}}
    }}

    log {{
        output file /var/log/caddy/hiveloom.access.log {{
            roll_size 50MiB
            roll_keep 5
        }}
    }}
}}
",
        acme_ca = acme_env.acme_ca(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_contains_host_and_email() {
        let out = render_caddyfile("h.example.com", "ops@example.com", AcmeEnv::Production, 3000);
        assert!(out.contains("h.example.com {"));
        assert!(out.contains("email ops@example.com"));
        assert!(out.contains("reverse_proxy 127.0.0.1:3000"));
        assert!(out.contains("X-Forwarded-Proto https"));
    }

    #[test]
    fn render_uses_production_acme_by_default() {
        let out = render_caddyfile("h.example.com", "ops@example.com", AcmeEnv::Production, 3000);
        assert!(out.contains("acme-v02.api.letsencrypt.org"));
        assert!(!out.contains("acme-staging"));
    }

    #[test]
    fn render_switches_to_staging_when_asked() {
        let out = render_caddyfile("h.example.com", "ops@example.com", AcmeEnv::Staging, 3000);
        assert!(out.contains("acme-staging-v02.api.letsencrypt.org"));
    }

    #[test]
    fn render_honors_custom_upstream_port() {
        let out = render_caddyfile("h.example.com", "ops@example.com", AcmeEnv::Production, 8080);
        assert!(out.contains("reverse_proxy 127.0.0.1:8080"));
    }
}
